// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/teacher/teacher.proto

package teacher

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Subjects      []string               `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	ClassSections []string               `protobuf:"bytes,4,rep,name=class_sections,json=classSections,proto3" json:"class_sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTeacherRequest) Reset() {
	*x = RegisterTeacherRequest{}
	mi := &file_api_teacher_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeacherRequest) ProtoMessage() {}

func (x *RegisterTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeacherRequest.ProtoReflect.Descriptor instead.
func (*RegisterTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterTeacherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterTeacherRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterTeacherRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *RegisterTeacherRequest) GetClassSections() []string {
	if x != nil {
		return x.ClassSections
	}
	return nil
}

type RegisterTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"` // added id if you want to return created teacher ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTeacherResponse) Reset() {
	*x = RegisterTeacherResponse{}
	mi := &file_api_teacher_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTeacherResponse) ProtoMessage() {}

func (x *RegisterTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTeacherResponse.ProtoReflect.Descriptor instead.
func (*RegisterTeacherResponse) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterTeacherResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterTeacherResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTeacherListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherListRequest) Reset() {
	*x = GetTeacherListRequest{}
	mi := &file_api_teacher_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherListRequest) ProtoMessage() {}

func (x *GetTeacherListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherListRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherListRequest) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{2}
}

type GetTeacherListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*Teacher             `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherListResponse) Reset() {
	*x = GetTeacherListResponse{}
	mi := &file_api_teacher_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherListResponse) ProtoMessage() {}

func (x *GetTeacherListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherListResponse.ProtoReflect.Descriptor instead.
func (*GetTeacherListResponse) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *GetTeacherListResponse) GetTeachers() []*Teacher {
	if x != nil {
		return x.Teachers
	}
	return nil
}

type GetTeacherByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherByIdRequest) Reset() {
	*x = GetTeacherByIdRequest{}
	mi := &file_api_teacher_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherByIdRequest) ProtoMessage() {}

func (x *GetTeacherByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *GetTeacherByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTeacherByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teacher       *Teacher               `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherByIdResponse) Reset() {
	*x = GetTeacherByIdResponse{}
	mi := &file_api_teacher_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherByIdResponse) ProtoMessage() {}

func (x *GetTeacherByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTeacherByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *GetTeacherByIdResponse) GetTeacher() *Teacher {
	if x != nil {
		return x.Teacher
	}
	return nil
}

type UpdateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Subjects      []string               `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	ClassSections []string               `protobuf:"bytes,5,rep,name=class_sections,json=classSections,proto3" json:"class_sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherRequest) Reset() {
	*x = UpdateTeacherRequest{}
	mi := &file_api_teacher_teacher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherRequest) ProtoMessage() {}

func (x *UpdateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTeacherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTeacherRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateTeacherRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *UpdateTeacherRequest) GetClassSections() []string {
	if x != nil {
		return x.ClassSections
	}
	return nil
}

type UpdateTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherResponse) Reset() {
	*x = UpdateTeacherResponse{}
	mi := &file_api_teacher_teacher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherResponse) ProtoMessage() {}

func (x *UpdateTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherResponse.ProtoReflect.Descriptor instead.
func (*UpdateTeacherResponse) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTeacherResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	mi := &file_api_teacher_teacher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTeacherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherResponse) Reset() {
	*x = DeleteTeacherResponse{}
	mi := &file_api_teacher_teacher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherResponse) ProtoMessage() {}

func (x *DeleteTeacherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherResponse.ProtoReflect.Descriptor instead.
func (*DeleteTeacherResponse) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTeacherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTeacherResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Teacher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Subjects      []string               `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	ClassSections []string               `protobuf:"bytes,5,rep,name=class_sections,json=classSections,proto3" json:"class_sections,omitempty"` // e.g., ["7A", "8B"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Teacher) Reset() {
	*x = Teacher{}
	mi := &file_api_teacher_teacher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Teacher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Teacher) ProtoMessage() {}

func (x *Teacher) ProtoReflect() protoreflect.Message {
	mi := &file_api_teacher_teacher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Teacher.ProtoReflect.Descriptor instead.
func (*Teacher) Descriptor() ([]byte, []int) {
	return file_api_teacher_teacher_proto_rawDescGZIP(), []int{10}
}

func (x *Teacher) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Teacher) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Teacher) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Teacher) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *Teacher) GetClassSections() []string {
	if x != nil {
		return x.ClassSections
	}
	return nil
}

var File_api_teacher_teacher_proto protoreflect.FileDescriptor

const file_api_teacher_teacher_proto_rawDesc = "" +
	"\n" +
	"\x19api/teacher/teacher.proto\x12\ateacher\x1a\x1cgoogle/api/annotations.proto\"\x87\x01\n" +
	"\x16RegisterTeacherRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x1a\n" +
	"\bsubjects\x18\x03 \x03(\tR\bsubjects\x12%\n" +
	"\x0eclass_sections\x18\x04 \x03(\tR\rclassSections\"]\n" +
	"\x17RegisterTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\x17\n" +
	"\x15GetTeacherListRequest\"F\n" +
	"\x16GetTeacherListResponse\x12,\n" +
	"\bteachers\x18\x01 \x03(\v2\x10.teacher.TeacherR\bteachers\"'\n" +
	"\x15GetTeacherByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x16GetTeacherByIdResponse\x12*\n" +
	"\ateacher\x18\x01 \x01(\v2\x10.teacher.TeacherR\ateacher\"\x95\x01\n" +
	"\x14UpdateTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x1a\n" +
	"\bsubjects\x18\x04 \x03(\tR\bsubjects\x12%\n" +
	"\x0eclass_sections\x18\x05 \x03(\tR\rclassSections\"K\n" +
	"\x15UpdateTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x14DeleteTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\x15DeleteTeacherResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\aTeacher\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x1a\n" +
	"\bsubjects\x18\x04 \x03(\tR\bsubjects\x12%\n" +
	"\x0eclass_sections\x18\x05 \x03(\tR\rclassSections2\xaf\x04\n" +
	"\x0eTeacherService\x12m\n" +
	"\x0fRegisterTeacher\x12\x1f.teacher.RegisterTeacherRequest\x1a .teacher.RegisterTeacherResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/teachers\x12g\n" +
	"\x0eGetTeacherList\x12\x1e.teacher.GetTeacherListRequest\x1a\x1f.teacher.GetTeacherListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/teachers\x12l\n" +
	"\x0eGetTeacherById\x12\x1e.teacher.GetTeacherByIdRequest\x1a\x1f.teacher.GetTeacherByIdResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/teachers/{id}\x12l\n" +
	"\rUpdateTeacher\x12\x1d.teacher.UpdateTeacherRequest\x1a\x1e.teacher.UpdateTeacherResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/teachers/{id}\x12i\n" +
	"\rDeleteTeacher\x12\x1d.teacher.DeleteTeacherRequest\x1a\x1e.teacher.DeleteTeacherResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/teachers/{id}B8Z6github.com/karanparmar2o/student-dashboard/api/teacherb\x06proto3"

var (
	file_api_teacher_teacher_proto_rawDescOnce sync.Once
	file_api_teacher_teacher_proto_rawDescData []byte
)

func file_api_teacher_teacher_proto_rawDescGZIP() []byte {
	file_api_teacher_teacher_proto_rawDescOnce.Do(func() {
		file_api_teacher_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_teacher_teacher_proto_rawDesc), len(file_api_teacher_teacher_proto_rawDesc)))
	})
	return file_api_teacher_teacher_proto_rawDescData
}

var file_api_teacher_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_teacher_teacher_proto_goTypes = []any{
	(*RegisterTeacherRequest)(nil),  // 0: teacher.RegisterTeacherRequest
	(*RegisterTeacherResponse)(nil), // 1: teacher.RegisterTeacherResponse
	(*GetTeacherListRequest)(nil),   // 2: teacher.GetTeacherListRequest
	(*GetTeacherListResponse)(nil),  // 3: teacher.GetTeacherListResponse
	(*GetTeacherByIdRequest)(nil),   // 4: teacher.GetTeacherByIdRequest
	(*GetTeacherByIdResponse)(nil),  // 5: teacher.GetTeacherByIdResponse
	(*UpdateTeacherRequest)(nil),    // 6: teacher.UpdateTeacherRequest
	(*UpdateTeacherResponse)(nil),   // 7: teacher.UpdateTeacherResponse
	(*DeleteTeacherRequest)(nil),    // 8: teacher.DeleteTeacherRequest
	(*DeleteTeacherResponse)(nil),   // 9: teacher.DeleteTeacherResponse
	(*Teacher)(nil),                 // 10: teacher.Teacher
}
var file_api_teacher_teacher_proto_depIdxs = []int32{
	10, // 0: teacher.GetTeacherListResponse.teachers:type_name -> teacher.Teacher
	10, // 1: teacher.GetTeacherByIdResponse.teacher:type_name -> teacher.Teacher
	0,  // 2: teacher.TeacherService.RegisterTeacher:input_type -> teacher.RegisterTeacherRequest
	2,  // 3: teacher.TeacherService.GetTeacherList:input_type -> teacher.GetTeacherListRequest
	4,  // 4: teacher.TeacherService.GetTeacherById:input_type -> teacher.GetTeacherByIdRequest
	6,  // 5: teacher.TeacherService.UpdateTeacher:input_type -> teacher.UpdateTeacherRequest
	8,  // 6: teacher.TeacherService.DeleteTeacher:input_type -> teacher.DeleteTeacherRequest
	1,  // 7: teacher.TeacherService.RegisterTeacher:output_type -> teacher.RegisterTeacherResponse
	3,  // 8: teacher.TeacherService.GetTeacherList:output_type -> teacher.GetTeacherListResponse
	5,  // 9: teacher.TeacherService.GetTeacherById:output_type -> teacher.GetTeacherByIdResponse
	7,  // 10: teacher.TeacherService.UpdateTeacher:output_type -> teacher.UpdateTeacherResponse
	9,  // 11: teacher.TeacherService.DeleteTeacher:output_type -> teacher.DeleteTeacherResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_teacher_teacher_proto_init() }
func file_api_teacher_teacher_proto_init() {
	if File_api_teacher_teacher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_teacher_teacher_proto_rawDesc), len(file_api_teacher_teacher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_teacher_teacher_proto_goTypes,
		DependencyIndexes: file_api_teacher_teacher_proto_depIdxs,
		MessageInfos:      file_api_teacher_teacher_proto_msgTypes,
	}.Build()
	File_api_teacher_teacher_proto = out.File
	file_api_teacher_teacher_proto_goTypes = nil
	file_api_teacher_teacher_proto_depIdxs = nil
}
