// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/student/student.proto

package student

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	RollNumber    string                 `protobuf:"bytes,3,opt,name=rollNumber,proto3" json:"rollNumber,omitempty"`
	Class         string                 `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	ParentName    string                 `protobuf:"bytes,6,opt,name=parentName,proto3" json:"parentName,omitempty"`
	ParentPhone   string                 `protobuf:"bytes,7,opt,name=parentPhone,proto3" json:"parentPhone,omitempty"`
	AdmissionDate string                 `protobuf:"bytes,8,opt,name=admissionDate,proto3" json:"admissionDate,omitempty"`
	Gender        string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStudentRequest) Reset() {
	*x = RegisterStudentRequest{}
	mi := &file_api_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStudentRequest) ProtoMessage() {}

func (x *RegisterStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStudentRequest.ProtoReflect.Descriptor instead.
func (*RegisterStudentRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterStudentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterStudentRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterStudentRequest) GetRollNumber() string {
	if x != nil {
		return x.RollNumber
	}
	return ""
}

func (x *RegisterStudentRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *RegisterStudentRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *RegisterStudentRequest) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *RegisterStudentRequest) GetParentPhone() string {
	if x != nil {
		return x.ParentPhone
	}
	return ""
}

func (x *RegisterStudentRequest) GetAdmissionDate() string {
	if x != nil {
		return x.AdmissionDate
	}
	return ""
}

func (x *RegisterStudentRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterStudentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStudentResponse) Reset() {
	*x = RegisterStudentResponse{}
	mi := &file_api_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStudentResponse) ProtoMessage() {}

func (x *RegisterStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStudentResponse.ProtoReflect.Descriptor instead.
func (*RegisterStudentResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterStudentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterStudentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStudentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentListRequest) Reset() {
	*x = GetStudentListRequest{}
	mi := &file_api_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentListRequest) ProtoMessage() {}

func (x *GetStudentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentListRequest.ProtoReflect.Descriptor instead.
func (*GetStudentListRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudentListRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

type GetStudentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*Student             `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentListResponse) Reset() {
	*x = GetStudentListResponse{}
	mi := &file_api_student_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentListResponse) ProtoMessage() {}

func (x *GetStudentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentListResponse.ProtoReflect.Descriptor instead.
func (*GetStudentListResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentListResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Class         int32                  `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"`
	Section       string                 `protobuf:"bytes,4,opt,name=section,proto3" json:"section,omitempty"`
	RollNo        string                 `protobuf:"bytes,5,opt,name=roll_no,json=rollNo,proto3" json:"roll_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_api_student_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Student) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *Student) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Student) GetRollNo() string {
	if x != nil {
		return x.RollNo
	}
	return ""
}

var File_api_student_student_proto protoreflect.FileDescriptor

const file_api_student_student_proto_rawDesc = "" +
	"\n" +
	"\x19api/student/student.proto\x12\astudent\x1a\x1cgoogle/api/annotations.proto\"\xa8\x02\n" +
	"\x16RegisterStudentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1e\n" +
	"\n" +
	"rollNumber\x18\x03 \x01(\tR\n" +
	"rollNumber\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x18\n" +
	"\asection\x18\x05 \x01(\tR\asection\x12\x1e\n" +
	"\n" +
	"parentName\x18\x06 \x01(\tR\n" +
	"parentName\x12 \n" +
	"\vparentPhone\x18\a \x01(\tR\vparentPhone\x12$\n" +
	"\radmissionDate\x18\b \x01(\tR\radmissionDate\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\"M\n" +
	"\x17RegisterStudentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x15GetStudentListRequest\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\"F\n" +
	"\x16GetStudentListResponse\x12,\n" +
	"\bstudents\x18\x01 \x03(\v2\x10.student.StudentR\bstudents\"x\n" +
	"\aStudent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x14\n" +
	"\x05class\x18\x03 \x01(\x05R\x05class\x12\x18\n" +
	"\asection\x18\x04 \x01(\tR\asection\x12\x17\n" +
	"\aroll_no\x18\x05 \x01(\tR\x06rollNo2\xe8\x01\n" +
	"\x0eStudentService\x12m\n" +
	"\x0fRegisterStudent\x12\x1f.student.RegisterStudentRequest\x1a .student.RegisterStudentResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/students\x12g\n" +
	"\x0eGetStudentList\x12\x1e.student.GetStudentListRequest\x1a\x1f.student.GetStudentListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/studentsB8Z6github.com/karanparmar2o/student-dashboard/api/studentb\x06proto3"

var (
	file_api_student_student_proto_rawDescOnce sync.Once
	file_api_student_student_proto_rawDescData []byte
)

func file_api_student_student_proto_rawDescGZIP() []byte {
	file_api_student_student_proto_rawDescOnce.Do(func() {
		file_api_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_student_student_proto_rawDesc), len(file_api_student_student_proto_rawDesc)))
	})
	return file_api_student_student_proto_rawDescData
}

var file_api_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_student_student_proto_goTypes = []any{
	(*RegisterStudentRequest)(nil),  // 0: student.RegisterStudentRequest
	(*RegisterStudentResponse)(nil), // 1: student.RegisterStudentResponse
	(*GetStudentListRequest)(nil),   // 2: student.GetStudentListRequest
	(*GetStudentListResponse)(nil),  // 3: student.GetStudentListResponse
	(*Student)(nil),                 // 4: student.Student
}
var file_api_student_student_proto_depIdxs = []int32{
	4, // 0: student.GetStudentListResponse.students:type_name -> student.Student
	0, // 1: student.StudentService.RegisterStudent:input_type -> student.RegisterStudentRequest
	2, // 2: student.StudentService.GetStudentList:input_type -> student.GetStudentListRequest
	1, // 3: student.StudentService.RegisterStudent:output_type -> student.RegisterStudentResponse
	3, // 4: student.StudentService.GetStudentList:output_type -> student.GetStudentListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_student_student_proto_init() }
func file_api_student_student_proto_init() {
	if File_api_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_student_student_proto_rawDesc), len(file_api_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_student_student_proto_goTypes,
		DependencyIndexes: file_api_student_student_proto_depIdxs,
		MessageInfos:      file_api_student_student_proto_msgTypes,
	}.Build()
	File_api_student_student_proto = out.File
	file_api_student_student_proto_goTypes = nil
	file_api_student_student_proto_depIdxs = nil
}
